data_reading:
  li_l1b_bck_nc_sift:
    group_keys: ['start_time']
    filter_patterns:
      [
        '{pflag}_{location_indicator},{data_designator},MTI{spacecraft_id}+LI-1B-BCK--{subtype}--{component1}-{component2}-{component3}-{purpose}-{format}_{oflag}_{originator}_{processing_time:%Y%m%d%H%M%S}_{facility_or_tool}_{environment}_{start_time:%Y%m%d%H%M%S}_{end_time:%Y%m%d%H%M%S}_{processing_mode}_{special_compression}_{disposition_mode}_{repeat_cycle_in_day:>04d}_{count_in_repeat_cycle:>04d}.nc',
        '{pflag}_{location_indicator},{data_designator},MTGI{spacecraft_id}+LI-1B-BCK--{subtype}--{component1}-{component2}-{component3}-{purpose}-{format}_{oflag}_{originator}_{processing_time:%Y%m%d%H%M%S}_{facility_or_tool}_{environment}_{start_time:%Y%m%d%H%M%S}_{end_time:%Y%m%d%H%M%S}_{processing_mode}_{special_compression}_{disposition_mode}_{repeat_cycle_in_day:>04d}_{count_in_repeat_cycle:>04d}.nc',
      ]
    geometry_definition: SwathDefinition
    kind: 'IMAGE'